=== f1nl0wt3ch/XML/finnkino.xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Events">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Event" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Title" type="xs:string"></xs:element>
							<xs:element name="OriginalTitle" type="xs:string"></xs:element>
							<xs:element name="ProductionYear" type="xs:gYear"></xs:element>
							<xs:element name="LengthInMinutes" type="xs:integer"></xs:element>
							<xs:element name="dtLocalRelease" type="xs:string"></xs:element>
							<xs:element name="Rating" type="xs:string"></xs:element>
							<xs:element name="EventType" type="xs:string"></xs:element>
							<xs:element name="Genres" type="xs:string"></xs:element>
							<xs:element name="ShortSynopsis" type="xs:string" minOccurs="0"></xs:element>
							<xs:element name="Synopsis" type="xs:string" minOccurs="0"></xs:element>
							<xs:element name="Cast" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Actor" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="FirstName" type="xs:string" minOccurs="0"></xs:element>
													<xs:element name="LastName" type="xs:string"></xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element><!-- cast -->
							<xs:element name="Directors">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Director">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="FirstName" type="xs:string"></xs:element>
													<xs:element name="LastName" type="xs:string"></xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element><!-- Directors -->
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== f1nl0wt3ch/XML/finnkino.xml
<?xml version="1.0"?>
<Events xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xsi:noNamespaceSchemaLocation="finnkino.xsd.xsd">
  <Event>
    <Title>24 viikkoa</Title>
    <OriginalTitle>24 Wochen</OriginalTitle>
    <ProductionYear>2016</ProductionYear>
    <LengthInMinutes>102</LengthInMinutes>
    <dtLocalRelease>2017-01-13T00:00:00</dtLocalRelease>
    <Rating>12</Rating>
    <EventType>Movie</EventType>
    <Genres>Draama</Genres>
    <ShortSynopsis>24 viikkoa on koskettava draamaelokuva naisen elämän vaikeimmasta valinnasta. Astrid on kuudennella kuulla raskaana, kun odottamaton diagnoosi pakottaa hänet pohtimaan tulevaisuuttaan uudelleen. Stand up -koomikko Astrid rakastaa työtään, manageri-miestään Markusta, yhdeksänvuotiasta tytärtään Neleä ja vitsailee lavalla toisesta raskaudestaan.</ShortSynopsis>
    <Synopsis>24 viikkoa on koskettava draamaelokuva naisen elämän vaikeimmasta valinnasta. Astrid on kuudennella kuulla raskaana, kun odottamaton diagnoosi pakottaa hänet pohtimaan tulevaisuuttaan uudelleen.

Stand up -koomikko Astrid rakastaa työtään, manageri-miestään Markusta, yhdeksänvuotiasta tytärtään Neleä ja vitsailee lavalla toisesta raskaudestaan. Kun käy ilmi, että vielä syntymätön lapsi ei olekaan terve, joutuvat Astrid ja Markus pohtimaan tulevaisuuttaan uudelleen. Alun luottavaisuus vaihtuu epäilyksi, kun diagnoosi paljastuu odotettua vakavammaksi. Astrid on lopulta tilanteessa, jossa vain hän voi päättää vauvan elämästä. Astridilla on mahdollisuus valita, mutta hänen on pakko tehdä päätös.

24 viikkoa ei ole elokuva abortin puolesta tai sitä vastaan, vaan se pakottaa pohtimaan kysymystä, johon kukaan ei voi vastata toisen puolesta. Koskettavan elokuvan käsikirjoitus on rakennettu perheiden, lääkäreiden ja kätilöiden haastatteluiden pohjalta. Astridin herkässä roolissa nähdään palkittu Julia Jentsch.

Kieli: saksa / Tekstitys: suomi &amp; ruotsi</Synopsis>
    <Cast>
      <Actor>
        <FirstName>Julia</FirstName>
        <LastName>Jentsch</LastName>
      </Actor>
      <Actor>
        <FirstName>Bjarne</FirstName>
        <LastName>Mädel</LastName>
      </Actor>
      <Actor>
        <FirstName>Johanna</FirstName>
        <LastName>Gastdorf</LastName>
      </Actor>
      <Actor>
        <FirstName>Emilia</FirstName>
        <LastName>Pieske</LastName>
      </Actor>
      <Actor>
        <FirstName>Maria-Victoria</FirstName>
        <LastName>Dragus</LastName>
      </Actor>
    </Cast>
    <Directors>
      <Director>
        <FirstName>Anne</FirstName>
        <LastName>Zohra Berrached</LastName>
      </Director>
    </Directors>
  </Event>
  <Event>
    <Title>American Pastoral</Title>
    <OriginalTitle>American Pastoral</OriginalTitle>
    <ProductionYear>2016</ProductionYear>
    <LengthInMinutes>108</LengthInMinutes>
    <dtLocalRelease>2017-01-20T00:00:00</dtLocalRelease>
    <Rating>Tulossa</Rating>
    <EventType>Movie</EventType>
    <Genres>Draama, Rikoselokuva</Genres>
    <ShortSynopsis>American Pastoral perustuu Phillip Rothin samannimiseen, Pulitzer-palkittuun romaaniin.</ShortSynopsis>
    <Synopsis>American Pastoral perustuu Phillip Rothin samannimiseen, Pulitzer-palkittuun romaaniin.</Synopsis>
    <Cast>
      <Actor>
        <FirstName>Ewan</FirstName>
        <LastName>McGregor</LastName>
      </Actor>
      <Actor>
        <FirstName>Jennifer</FirstName>
        <LastName>Connelly</LastName>
      </Actor>
      <Actor>
        <FirstName>Dakota</FirstName>
        <LastName>Fanning</LastName>
      </Actor>
      <Actor>
        <FirstName>David</FirstName>
        <LastName>Strathairn</LastName>
      </Actor>
      <Actor>
        <FirstName>Uzo</FirstName>
        <LastName>Aduba</LastName>
      </Actor>
      <Actor>
        <FirstName>Molly</FirstName>
        <LastName>Parker</LastName>
      </Actor>
    </Cast>
    <Directors>
      <Director>
        <FirstName>Ewan</FirstName>
        <LastName>McGregor</LastName>
      </Director>
    </Directors>
  </Event>
  <Event>
    <Title>Armoton maa</Title>
    <OriginalTitle>Armoton maa</OriginalTitle>
    <ProductionYear>2016</ProductionYear>
    <LengthInMinutes>90</LengthInMinutes>
    <dtLocalRelease>2017-01-20T00:00:00</dtLocalRelease>
    <Rating>16</Rating>
    <EventType>Movie</EventType>
    <Genres>Kotimainen</Genres>
    <ShortSynopsis>Pieni kylä Länsi-Lapissa lähellä Ruotsin rajaa. Eläkkeelle jäävä poliisi Lasse kuulee, että taposta tuomittu Jaakko on vapautunut vankilasta. Kylää aikanaan terrorisoinut Jaakko on ajautumassa törmäyskurssille Lassen pojan Erkin kanssa.</ShortSynopsis>
    <Synopsis>Pieni kylä Länsi-Lapissa lähellä Ruotsin rajaa. Eläkkeelle jäävä poliisi Lasse kuulee, että taposta tuomittu Jaakko on vapautunut vankilasta. Kylää aikanaan terrorisoinut Jaakko on ajautumassa törmäyskurssille Lassen pojan Erkin kanssa.

Yrittäessään estää kahta nuorta miestä vahingoittamasta toisiaan, vanhojen tekojen sovittaminen ja perheen salaisuuden säilyttäminen ajavat Lassen kahden tulen väliin. Pelastaakseen poikansa hänen on kohdattava menneisyytensä virheet.

Lopullinen välien selvittely käydään Lapin armottomassa erämaassa.</Synopsis>
    <Cast>
      <Actor>
        <FirstName>Ville</FirstName>
        <LastName>Virtanen</LastName>
      </Actor>
      <Actor>
        <FirstName>Antti</FirstName>
        <LastName>Holma</LastName>
      </Actor>
      <Actor>
        <FirstName>Mikko</FirstName>
        <LastName>Neuvonen</LastName>
      </Actor>
      <Actor>
        <FirstName>Jørgen</FirstName>
        <LastName>Langhelle</LastName>
      </Actor>
      <Actor>
        <FirstName>Outi</FirstName>
        <LastName>Mäenpää</LastName>
      </Actor>
      <Actor>
        <FirstName>Pernilla</FirstName>
        <LastName>August</LastName>
      </Actor>
      <Actor>
        <FirstName>Malin</FirstName>
        <LastName>Buska</LastName>
      </Actor>
    </Cast>
    <Directors>
      <Director>
        <FirstName>Jussi</FirstName>
        <LastName>Hiltunen</LastName>
      </Director>
    </Directors>
  </Event>

  <Event>
    <Title>Bleed for This</Title>
    <OriginalTitle>Bleed for This</OriginalTitle>
    <ProductionYear>2016</ProductionYear>
    <LengthInMinutes>116</LengthInMinutes>
    <dtLocalRelease>2017-01-06T00:00:00</dtLocalRelease>
    <Rating>12</Rating>
    <EventType>Movie</EventType>
    <Genres>Draama, Urheilu, Elämäkerta</Genres>
    <ShortSynopsis>Tositapahtumiin perustuva inspiroiva tarina nyrkkeilijä Vinny Pazienzasta (Miles Teller), joka pian voitettuaan maailmanmestaruustittelinsä joutuu rajuun auto-onnettomuuteen. Kuullessaan lääkäreiltä, ettei hän välttämättä kävelisi enää koskaan, aloittaa Pazienza valmistautumisen yhteen urheiluhistorian uskomattomimmista comebackeista.</ShortSynopsis>
    <Synopsis>Tositapahtumiin perustuva inspiroiva tarina nyrkkeilijä Vinny Pazienzasta (Miles Teller), joka pian voitettuaan maailmanmestaruustittelinsä joutuu rajuun auto-onnettomuuteen. Kuullessaan lääkäreiltä, ettei hän välttämättä kävelisi enää koskaan, aloittaa Pazienza valmistautumisen yhteen urheiluhistorian uskomattomimmista comebackeista.</Synopsis>
    <Cast>
      <Actor>
        <FirstName>Miles</FirstName>
        <LastName>Teller</LastName>
      </Actor>
      <Actor>
        <FirstName>Aaron</FirstName>
        <LastName>Eckhart</LastName>
      </Actor>
      <Actor>
        <FirstName>Katey</FirstName>
        <LastName>Sagal</LastName>
      </Actor>
      <Actor>
        <FirstName>Ciarán</FirstName>
        <LastName>Hinds</LastName>
      </Actor>
      <Actor>
        <FirstName>Ted</FirstName>
        <LastName>Levine</LastName>
      </Actor>
      <Actor>
        <FirstName>Christine</FirstName>
        <LastName>Evangelista</LastName>
      </Actor>
    </Cast>
    <Directors>
      <Director>
        <FirstName>Ben</FirstName>
        <LastName>Younger</LastName>
      </Director>
    </Directors>
  </Event>
  <Event>
    <Title>David Bowie Is</Title>
    <OriginalTitle>David Bowie Is</OriginalTitle>
    <ProductionYear>2013</ProductionYear>
    <LengthInMinutes>100</LengthInMinutes>
    <dtLocalRelease>2017-01-09T00:00:00</dtLocalRelease>
    <Rating>Luok_vap</Rating>
    <EventType>LiveEvent</EventType>
    <Genres>Taide, Event cinema (ei elokuva)</Genres>
    <ShortSynopsis>Dokumentti Lontoon Victoria and Albert Museumin (V&amp;A) uraauurtavasta taidenäyttelystä. David Bowie Is -näyttelyssä nähdään uskomaton kokoelma valokuvia, esiintymisasuja ja muita David Bowien arkiston harvinaisuuksia. Näyttely teki V&amp;A:n historiaa ja kiertää nyt maailman suurkaupunkeja.</ShortSynopsis>
    <Synopsis>Dokumentti Lontoon Victoria and Albert Museumin (V&amp;A) uraauurtavasta taidenäyttelystä. David Bowie Is -näyttelyssä nähdään uskomaton kokoelma valokuvia, esiintymisasuja ja muita David Bowien arkiston harvinaisuuksia. Näyttely teki V&amp;A:n historiaa ja kiertää nyt maailman suurkaupunkeja. Dokumentti on kuvattu näyttelyn viimeisenä iltana 11.8.2013 ja sen on ohjannut mm. BAFTA palkittu Hamish Hamilton.

Elokuvateatteriyleisö pääsee kokemaan näyttelyn aitiopaikalta ja erikoisvieraiden opastamana. Tarinoita David Bowien näyttelyn esineistöstä ovat kertomassa hänen yhteistyökumppaninsa, mm. japanilainen muotisuunnittelija Kansai Yamamoto ja Pulp-yhtyeen Jarvis Cocker. Näyttelyn kuraattorit Victoria Broackes ja Geoffrey Marsh kertovat unohtumattomista musiikkivideoista, esiintymisasuista sekä harvinaisista käsinkirjoitetuista sanoituksista, albumien kuvituksista ja päiväkirjamerkinnöistä, jotka paljastavat Bowien luovuuden.

Toiveuusinnat Finnkinon teattereissa maanantaina 9.1.2017! Liput tulevat myyntiin torstaina 1.12. klo 14.
