=== f1nl0wt3ch/XML/tuotteet.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- Sääntö 3, koska elementillä on alielementtejä -->
	<xs:element name="tuotteet">
		<xs:complexType>
			<xs:sequence>
				<!-- Sääntö 3, koska tuote-elementillä on alielementtejä -->
				<xs:element name="tuote" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<!-- tuote-elementin alielementit -->
							<!-- Sääntö 1, koska nimi on pelkkä elementti -->
							<xs:element name="nimi" type="xs:string" />
							<!-- Sääntö 1, koska kuvaus on pelkkä elementti -->
							<xs:element name="kuvaus" type="xs:string" minOccurs="0" />
							<!-- Sääntö 5, koska hinta-elementti on attribuutillinen elementti -->
							<xs:element name="hinta">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:decimal">
											<xs:attribute name="valuutta" type="xs:string"
												default="euro" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<!-- Sääntö 4, koska kuva-elementti on tyhjä -->
							<xs:element name="kuva" minOccurs="0" maxOccurs="10">
								<xs:complexType>
									<xs:attribute name="src" type="xs:anyURI" use="required" />
									<xs:attribute name="tyyppi" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<!-- tuote-elementin attribuutit -->
						<xs:attribute name="tuotekoodi" type="xs:unsignedInt"
							use="required" />
						<xs:attribute name="ryhma" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<!-- tuotteet-elementin attribuutit -->
			<!-- Sääntö2, koska attribuutti -->
			<xs:attribute name="paivitetty" type="xs:date" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== f1nl0wt3ch/XML/tuotteet.xml
<?xml version="1.0" encoding="UTF-8"?>
<tuotteet paivitetty="2012-08-15" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tuotteet.xsd">
	<tuote tuotekoodi="3871" ryhma="kamera">
		<nimi>Canon IXUS 220 HS -digikamera</nimi>
		<kuvaus>IXUS 220 HS yhdistää tehokkaan HS System -järjestelmän ja klassisen IXUS-muotoilun: ultralaajakulmainen 5x zoom-objektiivi, Full HD -videokuvaus ja hyvät hämäräkuvausominaisuudet ovat sulavalinjaisessa ruostumattomassa teräsrungossa.</kuvaus>
		<hinta valuutta="euro">149.90</hinta>
		<kuva src="IXUS220_1.jpg" tyyppi="jpg"/>
		<kuva src="XUS220_2.jpg" tyyppi="jpg"/>
	</tuote>
	<tuote ryhma="audio" tuotekoodi="11212">
		<nimi>Sennheiser HD 205 II DJ-kuulokkeet</nimi>
		<kuvaus>Sennheiser HD 205 II kuulokkeet ovat laadukkaat, ergonomisesti muotoillut ja hyvällä äänenlaadulla varustetut suljetut DJ-kuulokkeet.</kuvaus>
		<hinta>48.90</hinta>
	</tuote>
	<tuote ryhma="audio" tuotekoodi="38657">
		<nimi>Logitech Ultimate Ears 300 Noise-Isolating Earphones - nappikuulokkeet</nimi>
		<hinta valuutta="euro">39.90</hinta>
	</tuote>
	<tuote ryhma="oheislaitteet" tuotekoodi="16799">
		<nimi>Kingston 16 GB DataTraveler 100 G2 USB 2.0 -muistitikku</nimi>
		<kuvaus>Luotettava ja edullinen muistitikku tiedon helppoon siirtoon ja kuljetukseen. Tyylikäs viimeistely sisäänvedettävällä liittimellä. Soveltuu erinomaisesti esim. koti-, toimisto- tai koulukäyttöön.</kuvaus>
		<hinta valuutta="euro">17.90</hinta>
		<kuva src="Kingston16_1.gif" tyyppi="gif"/>
	</tuote>
</tuotteet>
