=== f1nl0wt3ch/XML/Hyvatietaa/hyvaTietaa2017.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="events">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="event" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="date" type="xs:date" />
							<xs:element name="time" type="xs:string" minOccurs="0" />
							<xs:element name="timezone" type="xs:string" minOccurs="0" />
							<xs:element name="name" type="xs:string" />
							<xs:element name="flag_day" type="xs:unsignedByte"
								minOccurs="0" />
							<xs:element name="alternate_names" type="xs:string"
								minOccurs="0" />
							<xs:element name="age" type="xs:unsignedShort"
								minOccurs="0" />
							<xs:element name="url" type="xs:string" />
							<xs:element name="location" type="xs:string"
								minOccurs="0" />
							<xs:element name="description" type="xs:string"
								minOccurs="0" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== f1nl0wt3ch/XML/Hyvatietaa/hyvaTietaa2017.xml
<?xml version="1.0" encoding="utf-8"?>
<events xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xsi:noNamespaceSchemaLocation="HyvaTietaa2017.xsd">
<event>
	<date>2017-01-13</date>
	<name>Joulurauhan loppumisen päivä</name>
	<url>https://fi.wikipedia.org/wiki/Joulurauha</url>
	<description>Joulurauha on kristillisten maiden perinne, jonka mukaan juhlapyhien aikana on ponnisteltava tavallista enemmän yhteiskuntarauhan säilyttämiseksi. Kirjoittamattoman lain mukaisesti sotatoimet pyrittiin keskeyttämään ja rauhanajan rikkomuksista annetut tuomiot olivat ankarampia kuin muulloin.

Ruotsissa ja siihen kuuluneessa Suomessa aikoinaan voimassa olleiden lakien mukaan joulurauha oli voimassa 20 vuorokautta alkaen jouluaatosta ja päättyen nuutinpäivänä.

Perinne on alkanut 1300-luvulla ja kukoisti ennen kaikkea 1700-luvulla.

Vaikka joulurauhan julistuksessa uhkaillaan tavallista ankarammilla rangaistuksilla joulurauhan aikana tehdyistä rikkomuksista, joulurauhalla ei ole ollut vuoden 1889 jälkeen mitään oikeudellista merkitystä.</description>
</event>
<event>
	<date>2017-01-13</date>
	<name>Nuutinpäivä</name>
	<url>https://fi.wikipedia.org/wiki/Nuuttipukki</url>
</event>
<event>
	<date>2017-01-13</date>
	<name>Perjantai, 13. päivä</name>
	<url>https://fi.wikipedia.org/wiki/Perjantai_13.</url>
</event>
<event>
	<date>2017-01-23</date>
	<name>Blue Monday</name>
	<alternate_names>vuoden masentavin päivä</alternate_names>
	<url>https://en.wikipedia.org/wiki/Blue_Monday_%28date%29</url>
	<description>Vuoden synkimmän päivän titteli tulee yhdistelmästä, jonka muodostavat kylmät arktiset sääolot, joulun erääntyvät laskut ja liian kaukana oleva palkkapäivä.</description>
</event>
<event>
	<date>2017-02-05</date>
	<name>J. L. Runebergin päivä</name>
	<flag_day>1</flag_day>
	<age>213</age>
	<url>https://fi.wikipedia.org/wiki/Johan_Ludvig_Runeberg</url>
	<description>Johan Ludvig Runeberg (5. helmikuuta 1804 Pietarsaari - 6. toukokuuta 1877 Porvoo) oli Suomen kansallisrunoilija. Hän oli suomalainen ruotsinkielinen runoilija, kirjailija ja toimittaja, jonka tuotanto on hyvin isänmaallista. Hän on ollut arvostettu myös Ruotsissa ja hänen tuotantonsa vaikutti suuresti koko ruotsinkieliseen kirjallisuuteen.</description>
</event>
<event>
	<date>2017-02-06</date>
	<name>Saamelaisten kansallispäivä</name>
	<age>100</age>
	<url>https://fi.wikipedia.org/wiki/Saamelaisten_kansallisp%C3%A4iv%C3%A4</url>
	<description>Saamelaisten kansallispäiväksi on valittu 6. helmikuuta, sillä tuona päivänä vuonna 1917 Pohjoismaiden saamelaiset aloittivat valtionrajat ylittävän keskinäisen yhteistyön. Yhteistyöstä päätettiin Norjan Trondheimin saamelaiskokouksessa, joka oli ensimmäinen laatuaan. Saamelaisten poliittisen itsetietoisuuden katsotaan syntyneen tuohon aikaan. Virikkeenä oli maailmalla leviävä kansallisuusaate. Saamelaisten pyrkimyksenä oli ensisijaisesti säilyttää mahdollisuus perinteisiin elinkeinoihinsa.</description>
</event>
<event>
	<date>2017-02-11</date>
	<name>112-päivä</name>
	<url>http://www.112-paiva.fi/</url>
	<description>Tarkista palohälyttimen paristot.

112-päivä on valtakunnallinen hätänumeropäivä, jolloin puhutaan arjen turvallisuudesta ja siitä, miten jokainen voi osaltaan huolehtia turvallisuudesta. Tavoitteena on tehdä Suomesta Euroopan turvallisin maa.

Useilla paikkakunnilla järjestetään tapahtumia, joiden tavoitteena on kiinnittää ihmisten huomio vahinkojen ja onnettomuuksien ennaltaehkäisemiseen. Monet tapaturmat, tulipalot ja rikokset on vältettävissä suunnitelmallisella toiminnalla. Lisäksi 112-päivänä jaetaan tietoa ja opastetaan ihmisiä toimimaan oikein hätätilanteissa.

112-päivä muistuttaa tietysti myös hätänumerosta 112 ja siitä, että tämä numero toimii kaikissa EU-maissa. Hätänumeroon soittamisesta opastetaan: milloin on tärkeää soittaa ja missä tilanteissa kannattaa valita jokin toinen numero. Hätätilanteessa 112 numeroon soittamista ei kannata epäröidä!</description>
</event>
<event>
	<date>2017-02-14</date>
	<name>Ystävänpäivä</name>
	<url>https://fi.wikipedia.org/wiki/Yst%C3%A4v%C3%A4np%C3%A4iv%C3%A4</url>
	<description>Ystävänpäivänä ystäviä muistetaan postikorteilla tai muilla tervehdyksillä.

Ystävänpäivää on Suomessa vietetty 1980-luvulta lähtien. Suomen kalenteriin ystävänpäivä on merkitty vuonna 1987. Se on muodostunut toiseksi suosituimmaksi korttipäiväksi joulun jälkeen. Päivän tunnuksena tunnetaan kautta maailman punainen sydän. Suomessa sen huomasi ensimmäisenä Tampereen Sydänyhdistys, joka keksi 1980-luvun alussa yhdistää ”punaisten sydänten juhlan” markkinointikampanjaansa. Seuraavaksi aiheesta kiinnostui Suomen Punainen Risti, joka painatti ensimmäiset ystävänpäiväkortit.

Kansainvälisestä Valentinuksen päivästä poiketen suomalainen ystävänpäivä on yleisemmin ystävien muistamisen, ei vain rakastavaisten juhlapäivä.</description>
</event>
<event>
	<date>2017-02-28</date>
	<name>Kalevalan päivä</name>
	<flag_day>1</flag_day>
	<alternate_names>suomalaisen kulttuurin päivä</alternate_names>
	<age>182</age>
	<url>https://fi.wikipedia.org/wiki/Kalevalan_p%C3%A4iv%C3%A4</url>
	<description>Kalevalan päivä on suomalaisen kulttuurin päivä, jota vietetään Suomen kansalliseepoksen, Kalevalan kunniaksi. Kalevalan päivää vietetään 28. helmikuuta, koska Elias Lönnrot allekirjoitti ja päiväsi Kalevalan ensimmäisen version, ns. Vanhan Kalevalan esipuheen 28. helmikuuta 1835.</description>
</event>
<event>
	<date>2017-02-28</date>
	<name>Laskiaistiistai</name>
	<url>https://fi.wikipedia.org/wiki/Laskiaistiistai</url>
	<description>Laskiainen on katolisen kirkon kirkon kevätpaaston alkajaisjuhla. Suomessa sanaa käytetään nykyisin laskiaistiistaista.

Laskiaista vietetään seitsemän viikkoa ennen pääsiäistä. Siihen kuuluvia juhlapäiviä ovat laskiaissunnuntai sekä kaksi päivää myöhemmin oleva laskiaistiistai. Laskiaisen jälkeen alkaa paastonaika, joka loppuu vasta pääsiäisenä. Oleellista paastonajalle oli liharuokien pois jättäminen ruokavaliosta, johon myös useat laskiaiseen liittyvät termit viittaavat. Laskiaistiistain jälkeinen tuhkakeskiviikko aloittaa 40 päivää kestävä paastoamisen.</description>
</event>
<event>
	<date>2017-03-01</date>
	<name>Talvirenkaiden käyttöpakko päättyy</name>
	<url>http://www.autonrengasliitto.fi/?id=23</url>
	<description>Nastattomilla talvirenkailla saa ajaa milloin vain.</description>
</event>
<event>
	<date>2017-03-01</date>
	<name>Tuhkakeskiviikko</name>
	<url>http://evl.fi/Evkirja.nsf/ppFI?OpenPage&amp;id=0027</url>
	<description>Tuhkakeskiviikko (lat. dies cinerum) on läntisen kristikunnan kirkkovuodessa juhla, joka aloittaa pääsiäistä edeltävän 40 päivän paastonajan. Tuhkakeskiviikko on kirkkovuodessa laskiaissunnuntaita seuraava keskiviikko, joka samalla lopettaa paastoa edeltävän karnevaali- tai laskiaisajan. Paastonaika jatkuu tuhkakeskiviikosta pääsiäislauantaihin. Tuhkakeskiviikon ja pääsiäislauantain väliin jää, nämä päivät mukaan luettuina, 46 päivää, mutta paastopäivien lukumääräksi tulee 40, koska paastonajan sunnuntait ja palmusunnuntai eivät ole paastopäiviä. 40 päivän paastonaika muistuttaa Jeesuksen paastosta autiomaassa ennen hänen julkisen toimintansa alkua. Sen tarkoituksena on valmistaa kristittyjä pääsiäisen viettoon, auttaa heitä miettimään syntejään ja puutteitaan sekä tekemään niistä parannusta, kehottaen heitä samalla lähimmäisenrakkauden tekoihin.

Tuhkakeskiviikko on saanut nimensä lännen kirkossa 1000-luvulla alkaneesta tavasta sirotella paastonajan aluksi ylleen tuhkaa katumuksen ja parannuksen merkiksi. 1100-luvulla tuli tavaksi, että sirottelussa käytetty tuhka tehtiin polttamalla edellisen vuoden palmusunnuntaina siunatut palmunoksat.

Tuhkekeskiviikon tekstit ja rukoukset puhuvat parannuksesta ja katumuksesta, ja jumalanpalvelus on tämän teeman sävyttämä. Liturgisena värinä on violetti, katumuksen väri.</description>
</event>
<event>
	<date>2017-03-08</date>
	<name>Kansainvälinen naistenpäivä</name>
	<age>42</age>
	<url>https://fi.wikipedia.org/wiki/Naistenp%C3%A4iv%C3%A4</url>
	<description>Kansainvälistä naistenpäivää on vietetty 8. maaliskuuta 1900-luvun alkupuolelta lähtien. Vuonna 1975, jota vietettiin kansainvälisenä naisten vuotena, Yhdistyneet kansakunnat vahvisti päivän vieton, ja se sai samalla nimen ”Yhdistyneiden kansakuntien naisten oikeuksien ja kansainvälisen rauhan päivä”.</description>
</event>
<event>
	<date>2017-03-19</date>
	<name>Minna Canthin päivä</name>
	<flag_day>1</flag_day>
	<alternate_names>tasa-arvon päivä</alternate_names>
	<age>173</age>
	<url>https://fi.wikipedia.org/wiki/Minna_Canthin_p%C3%A4iv%C3%A4</url>
	<description>Minna Canth, alkujaan Ulrika Wilhelmina o.s. Johnson, (19. maaliskuuta 1844 Tampere - 12. toukokuuta 1897 Kuopio) oli suomalainen kirjailija. Canth on tunnetuimpia suomalaisia 1880- ja 1890-luvun realisteja, ja hän kirjoitti novelleja, romaaneja ja näytelmiä. Hän oli ensimmäinen merkittävä suomenkielinen näytelmäkirjailija Aleksis Kiven jälkeen, ja ensimmäinen suomenkielinen sanomalehtinainen. Canthia pidetään ensimmäisenä nykysuomalaisena kirjailijana. Kirjallisuuden alalla hän oli realismin uranuurtaja.

Ajatusmaailmaltaan Canth oli vapaamielinen nuorsuomalainen ja sosialisti. Hänestä tuli tärkeä eurooppalaisten aatteiden välittäjä. Canth edisti naisten asemaa uusien koulutusmahdollisuuksien avulla ja oli suomenkielisen koulutuksen pioneereja. Ennen kuolemaansa Canth vaikutti noin puolen tusinan kuopiolaiskoulun taustalla (mm. Yhteiskoulu ja Kauppakoulu).</description>
</event>
<event>
	<date>2017-03-20</date>
	<name>Kevätpäiväntasaus</name>
	<url>https://fi.wikipedia.org/wiki/Kev%C3%A4tp%C3%A4iv%C3%A4ntasaus</url>
