=== f1nl0wt3ch/XML/OppimisTehtava3/tyontekijat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="tyontekijat"> 
	   <xs:complexType> 
	      <xs:sequence> 
			<xs:element name="tyontekija" maxOccurs="unbounded"> 
			   <xs:complexType> 
			      <xs:sequence> 
					<xs:element name="sukunimi" type="xs:string" /> 
					<xs:element name="etunimi" maxOccurs="3"> 
					   <xs:complexType> 
					      <xs:simpleContent> 
					         <xs:extension base="xs:string"> 
					           <xs:attribute name="kutsuma" type="xs:string" use="optional" /> 
					         </xs:extension> 
					      </xs:simpleContent> 
					   </xs:complexType> 
					</xs:element> 
					<xs:element name="palkka" type="xs:decimal" minOccurs="0" />
					<xs:element name="osasto" minOccurs="0"> 
					   <xs:complexType> 
					     <xs:attribute name="nimi" type="xs:string" use="required" />
					   </xs:complexType> 
					</xs:element> 
			      </xs:sequence> 
			      <xs:attribute name="asema" type="xs:string" use="optional" /> 
			      <xs:attribute name="id" type="xs:unsignedInt" use="required" /> 
			   </xs:complexType> 
			</xs:element> 
	      </xs:sequence> 
	   </xs:complexType> 
	</xs:element> 
</xs:schema>

=== f1nl0wt3ch/XML/OppimisTehtava3/tyontekijat.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<tyontekijat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tyontekijat.xsd">
    <tyontekija asema="Johtaja" id="1">
        <sukunimi>Virtanen</sukunimi>
        <etunimi>Matti</etunimi>
        <etunimi kutsuma="kyll채">Jukka</etunimi>
        <etunimi>Petteri</etunimi>
        <palkka>5000</palkka>
        <osasto nimi="Hallinto"/>
    </tyontekija>
    <tyontekija id="2">
        <sukunimi>Lahtinen</sukunimi>
        <etunimi kutsuma="kyll채">Liisa</etunimi>
        <palkka>6200</palkka>
    </tyontekija>
    <tyontekija id="3">
        <sukunimi>Virtanen</sukunimi>
        <etunimi kutsuma="kyll채">Leena</etunimi>
        <etunimi>Maija</etunimi>
        <palkka>3200</palkka>
    </tyontekija>
    <tyontekija asema="sihteeri" id="4">
        <sukunimi>Lahtinen</sukunimi>
        <etunimi kutsuma="kyll채">Jukka</etunimi>
        <osasto nimi="Myynti"/>
    </tyontekija>

</tyontekijat>
